spring:
    cloud:
        gateway:
          routes:
            - id: r1
              uri: lb://CUSTOMER-SERVICE
#              uri: http://localhost:8081/
              predicates:
                - Path=/api/customers/**
            - id: r2
              uri: lb://PRODUCT-SERVICE
#              uri: http://localhost:8082/

              predicates:
                - Path=/api/products/**